apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: gcr.io/cluster-proyecto-op2/springboot-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090